[package]
name = "polygon_transaction"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2.0", features = ["rustls", "legacy"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
dotenv = "0.15"
